organisation/urls.py
from django.urls import path
from . import views
from .views import StudentListView,StudentCreateView,load_courses,courses, OCreateView,OListView,cou, SearchResultsView,org,successs,SearchResultsView1,SearchResultsView2
urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search1/', SearchResultsView1.as_view(), name='search1_results'),
    path('search2/', SearchResultsView2.as_view(), name='search2_results'),
    path('', views. OCreateView.as_view(), name='organise'),
    path('addd/', views.OListView.as_view(), name='otlist'),
    path('cou/<int:organisation_id>',views.cou,name='cou'),
    path('success/',views.success,name='success'),
    path('org/<int:organisation_id>',views.org,name='org'),
    path('stu/<int:courses_id>/<int:organisation_id>',views.stu,name='stu'),
    path('successs/',views.successs,name='successs'),

    path('add/', views.StudentListView.as_view(), name='stlist'),
    path('create/', views.StudentCreateView.as_view(), name='add'),
    path('lcourses/', views.load_courses, name='load_courses'),
    path('courses/<int:id>',views.courses,name='courses'),
    path('organi/<int:id>',views.organi,name='organi'),
   
]

quizm/urls.py
from django.urls import path
from django.conf.urls import url
from .import views
from .views import start,start_quiz,question_view,logout,submit_quiz


urlpatterns = [
     path('',views.start,name='start'),
     path('startt/',views.start_quiz,name='startt'),
     path('questions/',views.question_view,name='questions'),
     path('logout',views.logout,name='logout'),
     path('answers/',views.submit_quiz,name='answers'),
     


]

webbrk/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('fusion.urls')),
    path('categorymanagement/', include('categorymanagement.urls')),
    path('use/', TemplateView.as_view(template_name='use.html'), name='use'), 
    path('or/', include('organisation.urls')),
    path('quiz/', include('quizm.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  
if settings.DEBUG:
        urlpatterns +=static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
                      

organisation/models.py
from django.db import models

# Create your models here.

class Organisation(models.Model):
  objects = models.Manager()
  name = models.CharField(max_length=60)

  def __str__(self):
        return self.name


class Courses(models.Model):
    objects = models.Manager()
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

   





class Student(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=100)
    organisation = models.ForeignKey(Organisation, on_delete=models.SET_NULL, null=True)
    courses = models.ForeignKey(Courses, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name  

organisation/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Student, Courses, Organisation

class OrganisationForm(forms.ModelForm):
    class Meta:
        model = Organisation
        fields = ['name']

class CoursesForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ['name']

# OrganisationFormSet = inlineformset_factory( Organisation,Courses, form=CoursesForm,fields=['name',], extra=1, can_delete=True)       
   

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name',]



# class StudentForm(forms.ModelForm):
#     class Meta:
#         model = Student
#         fields = ( 'organisation', 'courses','name')

    
        

organisation/views.py
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect,reverse
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy

from .models import Student, Courses,Organisation
from .forms import StudentForm, OrganisationForm,CoursesForm
from django.db.models import Q




# addorganisation---------------------------------------------------------
class OCreateView(CreateView):
    model = Organisation
    form_class = OrganisationForm
    success_url = reverse_lazy('otlist')    


class OListView(ListView):
    model = Organisation
    context_object_name = 'org'
    queryset = Organisation.objects.order_by('name')
    template_name = 'organisation/organisation_list.html ' 


class SearchResultsView(ListView):
    model = Organisation
    template_name = 'search_results.html'

    def get_queryset(self): 
        query = self.request.GET.get('q')
        object_list = Organisation.objects.filter(Q(name__icontains=query)).order_by('name')
        return object_list    


# addcourse---------------------------------------------------------


def cou(request,organisation_id):
    if request.method == 'POST':
        form = CoursesForm(request.POST)   

        if form.is_valid():
          a = form.save(commit=False)
          a.name = form.cleaned_data['name']
          a.organisation = Organisation.objects.get(pk = organisation_id)
          
        #   Courses.objects.create(name=name,organisation=a.organisation)
          a.save()
          return HttpResponseRedirect(reverse('success'))
          
    else:
        form = CoursesForm(request.POST)  
    return render(request, "organisation/courses_form.html", {'form': form})


def success(request):
    data=Courses.objects.all()
    data=Courses.objects.order_by('name')
    context = {
            'data':data 
    }
    return render(request,'coursel.html',context=context)

class SearchResultsView1(ListView):
    model = Courses
    template_name = 'search1_results.html'

    def get_queryset(self): 
        query = self.request.GET.get('q')
        object_list = Courses.objects.filter(Q(name__icontains=query)).order_by('name')
        return object_list    



def org(request,organisation_id):
    dataa=Courses.objects.filter(id=organisation_id)
    
    context = {
            'dataa':dataa 
    }
    return render(request,'orgl.html',context=context)


#addstudent----------------------------


def stu(request,courses_id,organisation_id):
    if request.method == 'POST':
        form = StudentForm(request.POST)      
        # print(form.is_valid())
        if form.is_valid():
          a = form.save()
          a.name = form.cleaned_data['name']
          
          a.courses = Courses.objects.get(pk = courses_id)
          a.organisation = Organisation.objects.get(pk = organisation_id)
          a.save()
        #   Student.objects.create(name=name,courses=a.courses,organisation=a.organisation)
          return HttpResponseRedirect(reverse('successs'))
    else:
        form = StudentForm(request.POST)  
    return render(request, "organisation/courses_form.html", {'form': form})


def successs(request):
    dta=Student.objects.all()
    dta = Student.objects.order_by('name')
    context = {
            'dta':dta 
    }
    return render(request,'sl.html',context=context)


class SearchResultsView2(ListView):
    model = Student
    template_name = 'search2_results.html'

    def get_queryset(self): 
        query = self.request.GET.get('q')
        object_list = Student.objects.filter(Q(name__icontains=query)|Q(courses__name__icontains=query)|Q(organisation__name__icontains=query)).order_by('name')
        return object_list 





















































# addstudent---------------------------------------------------------------

class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('stlist')  
   


def load_courses(request):
    organisation_id = request.GET.get('organisation')
    courses = Courses.objects.filter(organisation_id=organisation_id).order_by('name')
    return render(request, 'organisation/courses.html', {'courses': courses})    



class StudentListView(ListView):
    model = Student
    context_object_name = 'people'
    template_name = 'organisation/student_list.html ' 



def courses(request,id):    
    dataa = Student.objects.filter(id=id)
    return render(request,'cour.html',{'dataa': dataa})


def organi(request,id):    
    item = Student.objects.filter(id=id)
    return render(request,'org.html',{'item': item})

organisation/templates/organisation/course_list.html
{% extends 'layout.html' %}

{% block content %}

<div class="section-header text-center">
  <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Organisation management</h2>
  <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
</div>


<div class="container1">
          
  
  <table id="customers">
    <tr>
        <th>Courses</th>
        
        <!-- <th>ADD Courses</th> -->
        <!-- <th>Update</th> -->
       
    </tr>
    {% for organis in orgg %}
    <tr>
        <td style="color: black">{{ organis.name }}</td>
        <!-- <td><a href="{% url 'cor' %}"><button type="submit" >Add courses</button></a></td> -->
        
       
    </tr>
    
    {% endfor %}
</table>


{% endblock %}

organisation/templates/organisation/courses.html
<option value=""></option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

organisation/templates/organisation/courses_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="section-header text-center">
  <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Courses management</h2>
  <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
</div>


<div class="container1">
          

  <form method="post" id="sForm" action="" >
    {% csrf_token %}
    <label for="lname">name</label>
    <input type="text" id="name" name="name">

    
    <button type="submit">Save</button>
    
  </form>
</div>

{% endblock %}

organisation/templates/organisation/organisation_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="section-header text-center">
  <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Organisation management</h2>
  <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
</div>


<div class="container1">
          

  <form method="post" id="sForm" data-courses-url="{% url 'load_courses' %}" novalidate >
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    
  </form>
</div>

{% endblock %}

organisation/templates/organisation/organisation_list.html
{% extends 'layout.html' %}

{% block content %}

<div class="section-header text-center">
  <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Organisation management</h2>
  <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
</div>


<div class="container1">
  <form action="{% url 'search_results' %}" method="get">
    <input name="q" type="text" placeholder="Search...">
  </form>      
  
  <table id="customers">
    <tr>
        <th>Organisation</th>
        
        <th>ADD Courses</th>
        
        <!-- <th>Update</th> -->
       
    </tr>
    {% for organis in org %}
    <tr>
        <td style="color: black">{{ organis.name }}</td>
        <td><a href="{% url 'cou' organis.id %}"><button type="submit" >Add courses</button></a></td>
        
       
    </tr>
    
    {% endfor %}
</table>


{% endblock %}

organisation/templates/organisation/student_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="section-header text-center">
  <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Organisation management</h2>
  <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
</div>


<div class="container1">
          

  <form method="post" id="sForm" data-courses-url="{% url 'load_courses' %}" novalidate >
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_organisation").change(function () {
      var url = $("#sForm").attr("data-courses-url");
      var organisationId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'organisation': organisationId
        },
        success: function (data) {
          $("#id_courses").html(data);
        }
      });
    });
  </script>
  </div>

{% endblock %}

organisation/templates/organisation/student_list.html
{% extends 'layout.html' %}

{% block content %}

<div class="section-header text-center">
  <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Organisation management</h2>
  <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
</div>


<div class="container1">
          
  
  <table id="customers">
    <tr>
        <th>Students</th>
        
        <th>Courses</th>
        <!-- <th>Update</th> -->
       
    </tr>
    {% for student in people %}
    <tr>
        <td style="color: black">{{ student.name }}</td>
       
        <td><a href="{% url 'courses' student.id%}"><button type="submit" >click to courses</button></a></td>
       
    </tr>
    
    {% endfor %}
</table>
<a href="{% url 'add' %}"><button type="submit" style="margin:50px 250px;background-color: #4CAF50;color: white;padding: 12px 20px;border: none;">create student</button></a>

{% endblock %}